markdown: redcarpet
highlighter: pygments

permalink: pretty

title: effluence
url: http://sonnym.github.io/

paginate: 5

exclude: ["_examples/elm/0.14/*"]
keep_files: [".git", "examples/elm/0.14/*"]

lsi: true

gems: [jekyll-paginate, jekyll_example_embed, jekyll_elm]

excerpt_separator: "\n\n##\n\n"

collections:
  examples:
    output: true
  projects:
    output: false
