markdown: redcarpet
highlighter: pygments

permalink: pretty

title: effluence
url: https://sonnym.github.io/

timezone: 'America/New_York'

pagination:
  enabled: true
  per_page: 5
  sort_reverse: true

exclude: [
  "Gemfile",
  "Gemfile.lock",

  "package.json",
  "yarn.lock",
  "node_modules",

  "elm.json",
  "elm-stuff",
  "elm-stuff/0.19.0/Main.elmi",
  "elm-stuff/0.19.0/Main.elmo",

  "_examples/elm/0.1*",

  '*.xcf'
]

keep_files: [
  ".git",
  "examples/elm/0.14",
  "examples/elm/0.15"
]

lsi: true

livereload: true

plugins:
  - jekyll-paginate-v2
  - jekyll-minifier
  - jekyll_example_embed
  - jekyll_elm
  - jekyll_fancy_link

excerpt_separator: "\n\n##\n\n"

collections:
  examples:
    output: true

jekyll-minifier:
  exclude: 'atom.xml'
