markdown: redcarpet
highlighter: pygments

permalink: pretty

title: effluence
url: http://sonnym.github.io/

paginate: 5

lsi: true

gems: [jekyll-paginate, jekyll_example_embed, jekyll_elm]

excerpt_separator: "\n\n##\n\n"

collections:
  examples:
    output: true
    render: true
  projects:
    output: false
