markdown: redcarpet
highlighter: pygments

permalink: pretty

title: effluence
url: http://sonnym.github.io/

paginate: 5

exclude: [_posts/2014-05-05-writing-game-of-life-in-elm.markdown, _posts/2014-12-23-barebones-architecture-in-elm.markdown]

lsi: true

gems: [jekyll-paginate, jekyll_example_embed, jekyll_elm]

excerpt_separator: "\n\n##\n\n"

collections:
  examples:
    output: true
  projects:
    output: false
