markdown: redcarpet
highlighter: pygments

permalink: pretty

title: effluence
url: http://sonnym.github.io/

paginate: 5

lsi: false

gems: [jekyll_example_embed, jekyll_elm]

collections:
  examples:
    output: true
  projects:
    output: false
