highlighter: rouge

permalink: pretty

title: Sonny Michaud - Engineering Leader
url: https://sonnym.com

timezone: 'America/Chicago'

exclude: [
  "package.json",
  "yarn.lock",

  "elm.json",
  "elm-stuff",
  "elm-stuff/0.19.0/Main.elmi",
  "elm-stuff/0.19.0/Main.elmo",

  "_examples/elm/0.1*",

  '*.xcf'
]

keep_files: [
  ".git",
  "examples/elm/0.14",
  "examples/elm/0.15"
]

lsi: true

livereload: true

plugins:
  - jekyll-paginate-v2
  - jekyll-minifier

collections:
  examples:
    output: true

jekyll-minifier:
  exclude: 'atom.xml'
