markdown: redcarpet
highlighter: pygments

permalink: pretty

title: effluence
url: https://sonnym.github.io/

pagination:
  enabled: true
  per_page: 5
  sort_reverse: true

exclude: ["Gemfile", "Gemfile.lock", "elm*", "_examples/elm/0.14/*", '*.xcf']
keep_files: [".git", "examples/elm/0.14/*", "examples/elm/barebones_architecture"]

lsi: true

plugins:
  - jekyll-paginate-v2
  - jekyll-minifier
  - jekyll_example_embed
  - jekyll_elm
  - jekyll_fancy_link

excerpt_separator: "\n\n##\n\n"

collections:
  examples:
    output: true

jekyll-minifier:
  exclude: 'atom.xml'
